apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-pod
  name: example-pod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5500
  selector:
    run: example-pod
  type: LoadBalancer
