apiVersion: v1
kind: Service
metadata:
  labels:
    run: flask-app-1
  name: flask-app
spec:
  selector:
    run: flask-app-1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP