apiVersion: v1
kind: Service
metadata:
  labels:
    run: db-pod-1
  name: mysql
spec:
  selector:
    run: db-pod-1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP