pipeline {
    agent any
    environment {
        REGISTRY = "eu.gcr.io/lbg-mea-17"
        VERSION = "v2"
        YOUR_NAME = "JenkinsKubernetes"
    }
        stages {
        stage('Build and Push') {
            steps {
                echo "Building..."
                sh "docker build -t $REGISTRY/task1-app:$VERSION Task1"

            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                echo "YOUR_NAME = $YOUR_NAME"            
                echo "REGISTRY = $REGISTRY"
                echo "VERSION = $VERSION"
                }
        }
        stage('Push') {
            steps {
                sh "gcloud config set account chris-s-container-registry@lbg-mea-17.iam.gserviceaccount.com"
                sh "docker push $REGISTRY/task1-app:$VERSION"
            }
        }
         stage('Deploy') {
            steps {
                sh "gcloud config set account cs-jenkins-kubernetes@lbg-mea-17.iam.gserviceaccount.com"
                sh "kubectl create ns task1 || true"
                sh "sed -e 's,{{YOUR_NAME}},'$YOUR_NAME',g;' Task1/pod-w-services/app-config.yaml | tee Task1/pod-w-services/app-config-populated.yaml"
                sh "rm Task1/pod-w-services/app-config.yaml"
                sh "kubectl apply -f Task1/pod-w-services --namespace task1"
                sh "sleep 60"
                sh "kubectl get services --namespace task1"
            }
        }           
    }
    post {
        always {
            echo "these things will always happen"
            sh "docker system prune -f"
            sh "gcloud config set account null"
        }
    }
}