pipeline {
    agent any
    environment {
        REGISTRY = "eu.gcr.io/lbg-mea-17"
        VERSION = "v2"
        MYSQL_ROOT_PASSWORD = credentials("MYSQL_ROOT_PASSWORD") //comment 2
    }
    stages {
        stage('Build and Push') {
            steps {
                echo "Building..."
                sh "docker build -t $REGISTRY/chris-s-task2-db:$VERSION Task2/db"
                sh "docker build -t $REGISTRY/chris-s-task2-app:$VERSION Task2/flask-app"
         
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh "sleep 5"
                echo "PASSED"
                echo "lets go"
            }
        }
        stage('Push') {
            steps {
                sh "gcloud config set account chris-s-container-registry@lbg-mea-17.iam.gserviceaccount.com"
                sh "docker push $REGISTRY/chris-s-task2-db:$VERSION"
                sh "docker push $REGISTRY/chris-s-task2-app:$VERSION"       
            }
        }
        stage('Deploy') {
            steps {
                sh "gcloud config set account cs-jenkins-kubernetes@lbg-mea-17.iam.gserviceaccount.com"
                sh "kubectl create ns task2 || true"
                sh "sed -e 's,{{MYSQL_ROOT_PASSWORD}},'$MYSQL_ROOT_PASSWORD',g;' Task2/pod-w-services/db-password.yaml | kubectl apply -f - --namespace task2"
                sh "sed -e 's,{{VERSION}},'$VERSION',g;' Task2/pod-w-services/manifests/db-pod-manifest.yaml | tee Task2/pod-w-services/manifests/db-pod-manifest-populated.yaml"
                sh "sed -e 's,{{VERSION}},'$VERSION',g;' Task2/pod-w-services/manifests/app-deployment.yaml | tee Task2/pod-w-services/manifests/app-deployment-populated.yaml"
                sh "rm Task2/pod-w-services/manifests/db-pod-manifest.yaml Task2/pod-w-services/manifests/app-deployment.yaml"
                sh "kubectl apply -f Task2/pod-w-services/manifests --namespace task2"

                sh "sleep 60"
                sh "kubectl get services --namespace task2"
            }
        }
    }
    post {
        always {
            echo "these things will always happen"
            sh "docker system prune -f"
            cleanWs()
        }
    }
}