pipeline {
    agent any
    environment {
        DOCKER_USER = "chrissilcock33"
        MYSQL_ROOT_PASSWORD = "password123"
    }
    stages {
        stage('Build and Push') {
            steps {
                echo "Building..."
                sh "docker build -t $DOCKER_USER/task2-db Task2/db"
                sh "docker build -t $DOCKER_USER/task2-app Task2/flask-app"
                sh "docker push $DOCKER_USER/task2-db"
                sh "docker push $DOCKER_USER/task2-app"                
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh "sleep 5"
                echo "PASSED"
                echo "lets go"
            }
        }
        stage('Deploy') {
            steps {
                sh "docker stop \$(docker ps -q) || sleep 1"
                sh "docker rm \$(docker ps -qa) || sleep 1"
                sh "docker network inspect task2 && sleep 1 || docker network create task2"
                sh "docker run -d --network task2 --env MYSQL_ROOT_PASSWORD $DOCKER_USER/task2-db --name mysql"
                sh "docker run -d --network task2 --env MYSQL_ROOT_PASSWORD $DOCKER_USER/task2-app --name flaskapp"
                sh "docker run -d --network task2 -p 80:80 --mount type=bind,source=\$(pwd)/Task2/nginx/nginx.conf,target=/etc/nginx/nginx.conf nginx"
            }
        }
    }
    post {
        always {
            //sh "docker system prune -f"
        }
    }
}