apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-pod-2
  name: flask-app
spec:
  selector:
    run: example-pod-2
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
  type: ClusterIP